"""
decompile_99.py — Use pyghidra/Ghidra to fully decompile raw/99.exe
into a clean, well-organized C source file.

Usage:
    $env:GHIDRA_INSTALL_DIR = "C:\bin\ghidra_12.0.3_PUBLIC_20260210\ghidra_12.0.3_PUBLIC"
    python tools/decompile_99.py
"""

import os
import sys
from pathlib import Path

# Ensure GHIDRA_INSTALL_DIR is set
if "GHIDRA_INSTALL_DIR" not in os.environ:
    print("ERROR: GHIDRA_INSTALL_DIR not set. Set it and retry.")
    print("  $env:GHIDRA_INSTALL_DIR = 'C:\\bin\\ghidra_12.0.3_PUBLIC_20260210\\ghidra_12.0.3_PUBLIC'")
    sys.exit(1)

import pyghidra

BINARY = Path(__file__).resolve().parent.parent / "raw" / "99.exe"
OUTPUT = Path(__file__).resolve().parent.parent / "reverse_engineering_ref" / "decompiled" / "99.exe.pyghidra.c"


def main():
    print(f"Opening binary: {BINARY}")
    print(f"Output: {OUTPUT}")

    with pyghidra.open_program(str(BINARY)) as flat_api:
        program = flat_api.getCurrentProgram()
        listing = program.getListing()
        decompiler = flat_api.getDecompiler()

        # Collect all functions
        func_manager = program.getFunctionManager()
        functions = list(func_manager.getFunctions(True))  # True = iterate forward
        print(f"Found {len(functions)} functions")

        # Sort by entry point address
        functions.sort(key=lambda f: f.getEntryPoint().getOffset())

        lines = []
        lines.append("/*")
        lines.append(" * 99.exe — Decompiled by Ghidra via pyghidra")
        lines.append(f" * Ghidra version: {program.getGhidraVersion()}")
        lines.append(f" * Total functions: {len(functions)}")
        lines.append(" *")
        lines.append(" * Generated by tools/decompile_99.py")
        lines.append(" */")
        lines.append("")
        lines.append("/* ================================================================ */")
        lines.append("/*  TYPE DEFINITIONS                                                */")
        lines.append("/* ================================================================ */")
        lines.append("")

        # Collect typedefs from the data type manager
        dtm = program.getDataTypeManager()
        seen_types = set()

        # Add common typedefs
        lines.append("typedef unsigned char   byte;")
        lines.append("typedef unsigned char   uchar;")
        lines.append("typedef unsigned char   undefined1;")
        lines.append("typedef unsigned short  ushort;")
        lines.append("typedef unsigned short  undefined2;")
        lines.append("typedef unsigned short  word;")
        lines.append("typedef unsigned short  wchar16;")
        lines.append("typedef unsigned int    uint;")
        lines.append("typedef unsigned int    dword;")
        lines.append("typedef unsigned int    undefined4;")
        lines.append("typedef unsigned long   ulong;")
        lines.append("typedef unsigned long long  undefined8;")
        lines.append("typedef unsigned long   DWORD;")
        lines.append("typedef int             BOOL;")
        lines.append("typedef long            LONG;")
        lines.append("typedef long            LONG_PTR;")
        lines.append("typedef unsigned int    UINT;")
        lines.append("typedef unsigned int    UINT_PTR;")
        lines.append("typedef UINT_PTR        WPARAM;")
        lines.append("typedef LONG_PTR        LPARAM;")
        lines.append("typedef LONG_PTR        LRESULT;")
        lines.append("typedef char            CHAR;")
        lines.append("typedef CHAR *          LPCSTR;")
        lines.append("typedef unsigned int    ImageBaseOffset32;")
        lines.append("")

        # Data section globals
        lines.append("/* ================================================================ */")
        lines.append("/*  GLOBAL DATA / EXTERNS                                           */")
        lines.append("/* ================================================================ */")
        lines.append("")

        # Dump data labels (globals)
        data_sections = []
        for block in listing.getCodeBlocks():
            # Skip functions, only get data
            pass

        # Let's get memory blocks
        mem = program.getMemory()
        for block in mem.getBlocks():
            if not block.isInitialized():
                continue
            name = block.getName()
            start = block.getStart().getOffset()
            end = block.getEnd().getOffset()
            size = end - start + 1
            if block.isExecute():
                continue  # code section
            if size > 0x10000:
                continue  # skip large uninteresting sections
            lines.append(f"/* Section: {name}  (0x{start:08X} - 0x{end:08X}, {size} bytes) */")
            # Get data at this block
            data = listing.getDefinedDataAt(block.getStart())
            if data:
                lines.append(f"// {data.getDataType().getName()} {data.getDefaultValueRepresentation()}")
        lines.append("")

        # Function decompilations
        lines.append("/* ================================================================ */")
        lines.append("/*  DECOMPILED FUNCTIONS                                            */")
        lines.append("/* ================================================================ */")
        lines.append("")

        for i, func in enumerate(functions):
            name = func.getName()
            entry = func.getEntryPoint()
            addr = entry.getOffset()
            sig = func.getSignature().getPrototypeString()

            print(f"  [{i+1}/{len(functions)}] Decompiling {name} @ 0x{addr:08X}")

            try:
                decomp = decompiler.decompileFunction(func, 30, None)
                code = decomp.getDecompiledFunction().getC()
                lines.append(f"/* ----- {name} @ 0x{addr:08X} ----- */")
                lines.append(code)
                lines.append("")
            except Exception as e:
                lines.append(f"/* ----- {name} @ 0x{addr:08X} ----- */")
                lines.append(f"/* ERROR: Could not decompile: {e} */")
                lines.append("")
                print(f"    WARNING: Failed to decompile {name}: {e}")

        # Write output
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text("\n".join(lines), encoding="utf-8")
        print(f"\nDone! Wrote {len(lines)} lines to {OUTPUT}")


if __name__ == "__main__":
    main()
